name: "Deploy to GitHub Pages"
on:
    push:
        branches:
            - master
jobs:
  build_test:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ci & test
        run: |
          npm ci
          npm test

      - name: Build & doc
        run: |
          npm run jsdoc
          npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
